#!/usr/bin/env python
import socket
import sys
import re

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_address = ('localhost', 10006)
print >>sys.stderr, 'starting up on %s port %s' % server_address
sock.bind(server_address)
sock.listen(1)

events = {
        'get compass': (lambda: 180),
        'set compass': (lambda x: x*90)
        }

def get_event(s):
    for e in events:
        match = re.match(e, s)
        if match:
            if s.startswith('set'):
                arg = s.split()[-1]
                print 'setting to', arg
                return events[e](int(arg))
            else:
                print 'returning', e
                return events[e]()

while True:
    print >>sys.stderr, 'waiting for a connection'
    connection, client_address = sock.accept()
    try:
        while True:
            data = connection.recv(32)
            print >>sys.stderr, 'received "%s"' % data
            if data:
                print >>sys.stderr, 'sending data back to the client'
                connection.sendall(str(get_event(data)))
            else:
                break
            
    finally:
        connection.close()
