#!/usr/bin/env python

import socket
import sys

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_address = ('localhost', 10006)
print >>sys.stderr, 'connecting to %s port %s' % server_address
while True:
    sock.connect(server_address)
    try:
        sock.connect(server_address)
        message = raw_input('command: ')
        print >>sys.stderr, '    sending "%s"' % message
        sock.sendall(message)
        amount_received = 0
        amount_expected = len(message)
        
        data = sock.recv(32)
        amount_received += len(data)
        print >>sys.stderr, '    received "%s"' % data

    finally:
        print >>sys.stderr, 'closing socket'
        sock.close()
