#!/usr/bin/env python

import socket
import sys


while True:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_address = ('localhost', 5555)
    sock.connect(server_address)
    try:
        message = raw_input('command: ')
        sock.sendall(message)
        amount_received = 0
        amount_expected = len(message)
        
        data = sock.recv(32)
        amount_received += len(data)
        print data
    finally:
        sock.close()
