#!/usr/bin/env python
"""
Logs the position, heading and wind direction of the boat every ten seconds
"""

import sailbot
import time

boat = sailbot.Boat()
while True:
    boat.log()
    time.sleep(10)
