#!/usr/bin/env python
import sys

def convert_line(l):
    lat, lon = None, None
    for v in l.split():
        if v.startswith('lat='):
            lat = v[4:]
        if v.startswith('lon='):
            lon = v[4:]
    if '-1' in (lat, lon):
        return ''
    else:
        return 'T,{},{}\n'.format(lat, lon)

if __name__ == '__main__':
    lines = open(sys.argv[1]).readlines()
    with open('tracks', 'w') as out:
        out.write('type,latitude,longitude\n')
        for l in lines:
            out.write(convert_line(l))
